name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: companion
      run: cargo check --verbose
    - name: Run tests
      working-directory: companion
      run: cargo test --verbose

